### PR TITLE
Added methods to doc block of facade

### PR DESCRIPTION
**Pull request by promatik**
Fix for https://github.com/Laravel-Backpack/basset/issues/37.

### CODE REVIEW

**Comment by promatik** [comment]
@pxpm can you please confirm this fixes the issue?

**Comment by pxpm** [comment]
Hey @promatik I think your first commit worked better than the last one. 

I think the @mixin case is differently handled by editors, the @method annotation is more general. In my case using the mixin I couldn't get the auto-complete:
image

Using the methods in your first commit I get the full auto-complete:

image

**Comment by promatik** [comment]
@pxpm reverted that one with the mixin, can you test it now? 🙏

**Review by pxpm — APPROVED** [review]
working as expected on my vscode instance 👍

**Pull request merged**
